#include<windows.h>
#include<iostream>
#include<stdio.h>
using namespace std;
int main()
{
    int i;
    char h=3;
    system("cls");
    system("color f5");
    cout<<"\t\t\t From:- ASHU\n\n";
    Sleep(2000);
    cout<<"\t\t\t To:-LIFELINE"<<h<<"\n\n";
    Sleep(2000);
    cout<<"\t\t";
    for(i=0;i<42;i++)
    cout<<"-";
    cout<<"\n\n";
    system("color f4");
    Sleep(2000); 
    cout<< "\t\t\t\ti i i i i\n";
    Sleep(2000);
    cout<< "\t\t\t\ti i i i i\n";
    Sleep(2000);
        cout<<"\t\t\t      __i_i_i_i_i__\n";
     Sleep(2000);
     cout<<" \t\t\t      |"<< h << "         "<<h<< "|\n";
     Sleep(2000);
     cout<<" \t\t\t    __|"<<h<<"  29/11  "<<h<< "|__\n";
     Sleep(2000);
     cout<<" \t\t\t   |"<<h<<"   " <<h<<"        " <<h<<"  "<<h<< "|\n";
     Sleep(2000);
     cout<<"\t\t\t __|"<<h<<"   HAPPY   "<<h<<"   "<<h<< "|__\n" ;
     Sleep(2000); 
     cout<<"\t\t\t|  "<<h<<" " <<h<<"   BIRTHDAY      "   <<h<<"|\n";
     Sleep(2000);
     cout<<"\t\t\t|"<<h<<"    "<<h<<"    "<<h<<"   "<<h<<"   "<<h<<"   "<<h<<"|\n";
     Sleep(2000);
     cout<<"\t\t\t|"<<h<<" "<<h<<" "<<h<<" "<<h<<"   mr    "<<h<<" "<<h<<" "<<h<<" "<<h<<"|\n";
     Sleep(2000);
     cout<<"\t\t\t|_______________________|\n";
     cout<<"\n\n\n\n\n";
     system("pause");
     return 0;
     }